### ISSUE TITLE
convolve layer does not handle nodata sums correctly

### ISSUE THREAD

**Issue by richpsharp** [natcap/ecoshard#11]
If any pixel in an aggregated sum pixel is nodata the whole pixel is set to nodata. Instead the pixel should be nodata only if all the pixels aggregated are nodata.

**Comment by phargogh** [comment]
@richpsharp, I don't see anything about convolutions here in `ecoshard` ... did you mean to open this in the `pygeoprocessing` repo?

**Comment by phargogh** [comment]
Ugh, scratch that.  I had a typo in my search query.
